my_string=input('Сколько вешать в граммах? ')
print("Количество символов введённого текста равно",len(my_string),".")
print(my_string.upper())
print(my_string.lower())
print(my_string.replace(' ', ''))
print(my_string[0])
print(my_string[-1])